var read_published_global_tag_context_menu_tmpl =  ' <ul class="dropdown-menu multi-level" role="menu"> '
           + '   <li role="presentation"><a role="menuitem" tabindex="-1">Create Global Tag</a></li> '
           + '   <li role="presentation"><a role="menuitem" tabindex="-1">Clone Global Tag</a></li> '
           + '   <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1">Edit Global Tag</a></li> '
           + '   <li role="presentation" class="divider"></li> '
           + '   <li role="presentation" class="disabled" ><a role="menuitem" tabindex="-1" data-toggle="confirmation" >Publish Global Tag</a></li> '
           + '   <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" data-toggle="confirmation" >Invalidate Global Tag</a></li> '
           + '   <li role="presentation" class="divider"></li> '
           + '   <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1">Add Payload IOV</a></li> '
           + ' </ul> ';
