<script type="text/javascript" src="/js/libs/jquery-2.1.0.min.js"></script>
<script type="text/javascript" src="/js/libs/bootstrap.min.js"></script>
<script type="text/javascript" src="/js/libs/handlebars-1.1.2.js"></script>
<!--script type="text/javascript" src="/js/libs/ember-1.3.1.js"></script-->
<script type="text/javascript" src="/js/libs/typeahead.bundle.min.js"></script>
<script type="text/javascript" src="/js/rfore.js"></script>