var read_new_global_tag_context_menu_tmpl =  ' <ul class="dropdown-menu multi-level" role="menu"> '
           + '   <li role="presentation"><a role="menuitem" tabindex="-1" onclick="window.create_global_tag()">Create Global Tag</a></li> '
           + '   <li role="presentation"><a role="menuitem" tabindex="-1" onclick="window.clone_global_tag()">Clone Global Tag</a></li> '
           + '   <li role="presentation"><a role="menuitem" tabindex="-1" onclick="window.edit_global_tag()">Edit Global Tag</a></li> '
           + '   <li role="presentation" class="divider"></li> '
           + '   <li role="presentation"><a role="menuitem" tabindex="-1" onclick="window.publish_global_tag()" data-toggle="confirmation" >Publish Global Tag</a></li> '
           + '   <li role="presentation"><a role="menuitem" tabindex="-1" onclick="window.invalidate_global_tag()" data-toggle="confirmation" >Invalidate Global Tag</a></li> '
           + '   <li role="presentation" class="divider"></li> '
           + '   <li role="presentation" ><a role="menuitem" tabindex="-1" onclick="window.create_globaltag_iov()">Add Payload IOV</a></li> '
           + ' </ul> ';
